<?php

global $airport;
$airport = array(
    "Honolulu, Hawaii" => "HNL",
    "Lake Louise, Canada" => "YYC",
    "Berlin, Germany" => "SXF",
    "Barcelona, Spain" => "BCN",
    "Corsica, France" => "AJA",
    "Miyako Island, Japan" => "MMY",
    "Banff, Canada" => "YYC",
    "Victoria, Canada" => "YYJ",
    "Playa Del Carmen, Mexico" => "CUN",
    "Barbados, Caribbean Islands" => "BGI",
    "Anaheim, California, USA" => "SNA",
    "Grand Teton National Park, USA" => "JAC",
    "Val Thorens, France" => "PAR",
    "Patagonia, Argentina" => "SCL",
    "Macau, China" => "MFM",
    "Seattle, Washington, USA" => "SEA",
    "Vancouver, Canada" => "YVR",
    "Osaka, Japan" => "OSA",
    "Lapland, Finland" => "HEL",
    "Ibo Island, Mozambique" => "MPM",
    "Saigon, Vietnam" => "SGN",
    "Belize, Caribbean Islands" => "BZE",
    "Zurich, Switzerland" => "ZRH",
    "Fort Lauderdale, Florida" => "FLL",
    "Machu Picchu, Peru" => "CUZ",
    "Jasper, Canada" => "YJA",
    "Reykjavik, Iceland" => "KEF",
    "Bergen, Norway" => "BGO",
    "Salzburg, Austria" => "VIE",
    "Cairo, Egypt" => "CAI",
    "St. Moritz, Switzerland" => "LUG",
    "Aspen, Colorado, USA" => "ASE",
    "Whistler, Canada" => "YVR",
    "Grindelwald, Switzerland" => "ZRH",
    "Sydney, Australia" => "SYD",
    "San Juan, Puerto Rico" => "SJU",
    "Orlando, Florida, USA" => "ORL",
    "Nice, France" => "NCE",
    "Cancun, Mexico" => "CUN",
    "Okinawa, Japan" => "OKA",
    "Lisbon, Portugal" => "LIS",
    "Kapolei, Hawaii" => "HNL",
    "Antigua, Caribbean Islands" => "ANU",
    "Seoul, South Korea" => "SEL",
    "Beijing, China" => "PEK",
    "Breckenridge, Colorado, USA" => "EGE",
    "Tokyo, Japan" => "TYO",
    "Hong Kong" => "HKG",
    "Nepal" => "KTM",
    "Huangshan, China" => "TXN",
    "Tibet" => "NGQ",
    "Grand Canyon National Park, Arizona, USA" => "LAS",
    "Anchorage, Alaska, USA" => "ANC",
    "Portland, Oregon, USA" => "PDX",
    "Negril, Jamaica" => "MBJ",
    "Scheveningen, The Netherlands" => "RTM",
    "Rio de Janeiro, Brazil" => "RIO",
    "Santorini, Greece" => "JTR",
    "Wildwood, New Jersey, USA" => "PHL",
    "Tel Aviv, Israel" => "TLV",
    "Ko Lanta, Thailand" => "KBV",
    "Guadeloupe" => "PTP",
    "Coral Coast, Fiji" => "SUV",
    "St Martin, Caribbean Islands" => "SXM"
);

$description = array(
    "Honolulu, Hawaii" => "Honolulu, on the island of Oahu, is the capital and largest city of the state of Hawaii and a legendary destination for surfing and enjoying the spectacular beaches. Oahu is the Hawaiian island that has it all—untouched tropical landscapes as well as a stimulating urban vibe. You can explore the beaches and gentle waves of Kailua, or take in nightlife in buzzing Honolulu, home to a vibrant Chinatown and burgeoning arts scene. Life is still appealingly slow-paced on the northern and eastern shores, where razor-edged mountains descend to spectacular beaches. A thriving traditional culture, plus top-notch historic sites such as the royal Iolani Palace and Pearl Harbor, spice up the mix here as well.",

    "Lake Louise, Canada" => "Lake Louise is a beautiful mountain lake in the middle of Banff National Park in the Alberta Rockies region of Alberta, Canada. Lake Louise is what makes Banff National Park the phenomenon it is, an awe-inspiring natural feature that is impossible to describe without resorting to shameless clichés. Standing next to the serene, implausibly turquoise lake, the natural world feels - and is - tantalizingly close, with a surrounding amphitheater of finely chiseled mountains that hoist Victoria Glacier up for all to see.",

    "Berlin, Germany" => "Berlin is a big multicultural metropolis but deep down it maintains the unpretentious charm of an international village. Locals follow the credo 'live and let live' and put greater emphasis on personal freedom and a creative lifestyle than on material wealth and status symbols. Cafes are jammed at all hours, drinking is a religious rite and clubs keep going until the wee hours or beyond. Size-wise, Berlin is pretty big but its key areas are wonderfully compact and easily navigated on foot, by bike or by using public transport. Berlin's combo of glamour and grit is bound to mesmerize anyone keen to explore its vibrant culture, cutting-edge architecture, fabulous food, intense parties and tangible history.",

    "Barcelona, Spain" => "Barcelona is the capital city of the Catalonia community in Spain and is known for its unique blend of Catalan culture, distinctive architecture, lively nightlife and trendy, stylish hotels. Barcelona has a rich cultural heritage, which has lended itself to become a major tourist destination today. Renowned architectural works of Antoni Gaudí and Lluís Domènech i Montaner have been designated UNESCO World Heritage Sites. No matter where you go in Barcelona, you're certain to be dazzled by its beauty and rich culture.",

    "Corsica, France" => "Jutting out of the Mediterranean like an impregnable fortress, Corsica resembles a miniature continent, with astounding geographical diversity. Within half an hour, the landscape morphs from glittering bays, glitzy coastal cities and fabulous beaches to sawtooth peaks, breathtaking valleys, dense forests and enigmatic hilltop villages. Holidays in Corsica will therefore be incredibly varied: from hiking and canyoning to working your tan, enjoying a leisurely cruise, delving into the island’s rich history and sampling local specialities. Though Corsica has officially been part of France for more than 200 years, it feels different from the mainland in everything from customs and cuisine to language and character, and that’s part of its appeal. Locals love talking about their Corsican identity so plenty of engaging evenings await, especially if the holy trilogy of food, wine and melodious Corsican music are involved.",

    "Miyako Island, Japan" => "Miyako Island, located 300 kilometers south of Okinawa Main Island, is known for some of Japan's best beaches and as a great destination for snorkeling and diving in the coral reefs. Some intensive beach therapy can be engaged in here. In the southwest corner of the main island, Miyako-jima, is Maehama, perhaps Japan's finest beach, and across the bridge on the adjacent tiny island of Kurima-jima lies the gorgeous Nagamahama Beach. Throughout the Miyako islands you can find bright white sand and emerald, turquoise, and cobalt waters. During your time here, you’ll be sure to embrace the Okinawan slow, relaxed lifestyle, enjoy Okinawan cuisine and culture. In Miyako, you can do everything from lounge on the beautiful beaches, play beach volleyball, golf, make your own shisa, listen to the sanshin, or, if you're feeling very competitive, participate in the local Strongman Triathlon, held every April.",

    "Banff, Canada" => "Set in the heart of Banff National Park and snugly embraced by Alberta's Rocky Mountains, the little town of Banff boasts a big, worldwide reputation. Its charming streets are abuzz year round due to an annual influx of millions of visitors, and this famous mountain resort town caters accordingly with world-class shopping, dining and an array of accommodation, from cabins and campgrounds to bed and breakfasts and Banff chateau-style hotels. At first sight it's apparent why the world is in love with Banff. From the ever-watchful Cascade Mountain to the picturesque Bow River, the community is blessed with a spectacular natural setting, woven with parks, woods and trails. Banff is ideal for extensive hiking, biking, and skiing. After a long day, you can unwind in one of the several hot springs and spas. Banff, Canada is the ideal getaway that allows for both fun and relaxation for you and the entire family in one of the most beautiful places in the world.",

    "Victoria, Canada" => "Victoria, British Columbia's photogenic capital, is a walkable, livable seaside city of fragrant gardens, waterfront paths, engaging museums, and beautifully restored 19th-century architecture. In summer, the Inner Harbour—Victoria's social and cultural center—buzzes with visiting yachts, horse-and-carriage rides, street entertainers, and excursion boats heading out to visit pods of friendly local whales. Victoria and all the exciting experiences to be had are easily accessible as the city has more cycling routes than any other Canadian city, providing a great way to explore the beautiful landscape, and various tearooms, antiques shops, and galleries throughout. Yes, it might be a bit touristy, but Victoria's good looks, gracious pace, and manageable size are instantly beguiling, especially if you stand back to admire the mountains and ocean beyond.",

    "Playa Del Carmen, Mexico" => "Playa Del Carmen is a coastal resort town in Mexico that lines the Caribbean shoreline. It is known for its palm-lined beaches and coral reefs. Tourist activity centers on Quinta Avenida, or Fifth Avenue, which is a pedestrian walkway that is lined with hundreds of shops, restaurants, and nightspots ranging from laid-back bars to dance clubs. There are many small boutique hotels around Fifth Avenue and on the beach that lend themselves to an even more authentic and memorable Playa Del Carmen experience.",

    "Barbados, Caribbean Islands" => "Barbados is a lush West Indian island in the Caribbean with clear, turquoise waters, soft sand beaches, and catamaran cruises. To the west coast of Barbados, you will find calm waters making for a very pleasant swimming experience. To the east, there are massive, competition-caliber waves. Bridgetown, the capital, is a cruise-ship port that boasts rich historical architecture ranging from colonial buildings to a synagogue founded in the 17th century. Besides beaches, the island is home to many botanical gardens and cave formations.",

    "Anaheim, California, USA" => "Anaheim is a city outside of Los Angeles. It’s home to the Disneyland Resort, a massive complex of family-friendly, Disney-themed rides, restaurants, hotels, and shops. For a change of pace, check out Block at Orange, an all-in-one shopping, dining and entertainment promenade. You can also explore Universal Studios Hollywood, a film studio and theme park in Los Angeles. With tons of exciting attractions, you and your family are guarenteed to have a fun and memorable vacation.",

    "Grand Teton National Park, USA" => "Grand Teton National Park, located in the state of Wyoming, USA, is home to what is probably the most iconic mountain range in the United States. These showy peaks, reflected in a string of easily accessed glacial lakes, come close to most people’s picture-postcard image of alpine splendor and will send a shiver of excitement down the spine of even the least vertically inclined. Buckle up and climb a Teton peak, backpack the Teton Crest and then recover with the sophisticated charms of Jackson Hole. Rarely are the delights of the front- and backcountry so close together. This national park is an almost pristine ecosystem and the same species of flora and fauna that have existed since prehistoric times can still be found there. Many of the West’s iconic animals – elk, bears, bald eagles among them – call this park home. The park also has a rich cultural history with old homesteads and cattle ranches to explore and photograph. Walk on a trail built by the Civilian Conservation Corps or one that Native Americans or fur trappers might have used in the 1820s. Ride a bike or paddle a canoe. There is something for everyone. Whatever your interests, Grand Teton has something for you.",

    "Val Thorens, France" => "Val Thorens is a ski resort located Savoie, France high in the French Alps. Val Thorens is the highest Alpine Skiing resort in Europe, with the town itself at 2300m above sea level. This also makes it one of the most snow assured in Europe, with the ski season extending to early May. The resort's position at the head of the Belleville Valley, surrounded by a horseshoe of dramatic peaks, is truly spectacular. On a fine day this offers a world class winter panorama. Val Thorens is a skiing wonderland with something to offer for skiers and boarders of all levels and abilities. When you are not hitting the slopes, you’ll be sure to find fun in town at the many shops, boutiques, bars and restaurants. Whether you are looking for an epic skiing adventure or just some rest and relaxation in a winter wonderland, Val Thorens is the place for you.",

    "Patagonia, Argentina" => "On South America’s southern frontier, nature grows wild, barren and beautiful. Spaces are large, as are the silences that fill them. For the newly arrived, such emptiness can be as impressive as the sight of Patagonia’s jagged peaks, pristine rivers and dusty backwater oases. In its enormous scale, Patagonia offers an innumerable wealth of potential experiences and landscapes. In addition to its natural beauty, Patagonia is filled with great charm. Here almost all tourism is a rural and very homemade affair where informal, family-run hotels or hospedajes are the norm and hosts will make you feel right at home. You would struggle to find a more intensely beautiful, rugged and diverse countryside, from vivid green alpine meadows dotted with wildflowers, to glacier fields stretching as far as the eye can see.",

    "Macau, China" => "Best known globally as the 'Vegas of China', Macau is world-famous as a gaming destination and has also begun attracting visitors with an increasing array of shows, entertainment, and nightlife. One of its more striking landmarks is 338m-high Macau Tower, with sweeping city views. The city's historic center, with its rich blend of Chinese and European architecture and culture, has been designated a UNESCO World Heritage Site. Ancient Chinese temples sit on streets paved with traditional Portuguese tile. The sound of Cantonese fills the air on streets with Portuguese names. You can eat Chinese congee for breakfast, enjoy a Portuguese lunch of caldo verde soup and bacalhau (cod) fritters, and dine on hybrid Macanese fare such as minchi (ground beef or pork, often served over rice). Whether you're down for relaxing on Macau's beaches or going out to take in the exhiliarating Macau nightlife, you're surely to have vacation you won't ever forget.",

    "Seattle, Washington, USA" => "Seattle is surrounded by water, mountains, evergreen forests, and contains thousands of acres of parkland. As Washington’s largest city, it is home to a large tech industry, with Microsoft and Amazon headquarters in its metropolitan area. Seattle’s most iconic feature is the Space Needle, an observation tower where visitors can overlook the city while dining at its restaurants. Seattle is also home to four major art museums and has over 100 commercial art galleries. While in Seattle, don't forget to visit the world famous Pike Place Market. The city of Seattle makes for a wonderful destination with plenty to explore.",

    "Vancouver, Canada" => "Vancouver is a bustling oceanside city in British Columbia, and is among Canada’s densest, most ethnically and linguistically diverse cities. A popular filming location, it’s surrounded by mountains, and also has thriving art, theatre and music scenes. Vancouver offers you the best of both worlds with outstanding opportunities for outdoor adventure and the sophisticated amenities of a world-class city. While Vancouver is known for its temperate climate, the surrounding snow-covered mountains are perfect for winter sports and breathtaking views of the city twinkling below. Vancouver is one of the few places in the world where it's possible to ski in the morning and sail in the afternoon.",

    "Osaka, Japan" => "Osaka is a large port city and commercial center on the Japanese island of Honshu. It's known for its modern architecture, nightlife and hearty street food. The 16th-century shogunate Osaka Castle, which has undergone several restorations, is its main historical landmark. It's surrounded by a moat and park with plum, peach and cherry-blossom trees. Sumiyoshi-taisha is among Japan’s oldest Shinto shrines. With so much beauty, history, both modern and ancient architecture, and culture to explore, Osaka makes for a magnificently unforgettable experience.",

    "Lapland, Finland" => "Lapland is Finland’s northernmost region where the Northern Lights or Aurora Borealis are visible roughly 200 nights a year - or every other clear night. You can gaze up into the nightsky while in the comfort of a range of purpose-built spaces from glass igloos to luxury suites. For the adventurous, there are the more traditional ways to go Aurora spotting, such as snowshoeing, cross-country skiing or snowmobile and sled dog touring. In the summer, Finnish Lapland bathes in sunlight for nearly three months. ‘Midnight sun’, as this phenomenon is called, calls for exciting activities such as hiking on the beautiful fells or visiting cultural events such as the Midnight Sun Film Festival in Sodankylä. Regardless of the time of year that you choose to visit, you and the entire family will most certainly be enchanted by the majestic beauty of Lapland.",

    "Ibo Island, Mozambique" => "Ibo, with its gorgeous and completely derelict colonial ruins, molasses-slow pace of life beneath the mango trees, and clutch of gorgeous heritage guesthouses, is the capital of the Quirimbas Archipelago, and one of the most gorgeous ‘insider’ spots in southern Africa. The Quirimbas themselves, with their 400 small tropical islands set in a landscape of dramatically shifting tides, are a picture-postcard of the romance of coastal Africa -- leaf-shaped Arab dhows skimming through the shallows, white sands, turquoise waters and swaying palms. In addition to the breath taking sights, you can enjoy snorkeling, sea kayaking, swimming and fishing. When you’ve had your fill of the open water, you can sit back and enjoy a relaxing massage with a local fruity drink in hand. You and the entire family will definitely enjoy the piece of paradise found on Ibo Island.",

    "Saigon, Vietnam" => "Ho Chi Minh City (HCMC), also commonly known as Saigon, is Vietnam at its most dizzying: a high-octane city of commerce and culture that has driven the country forward with its pulsating energy. A chaotic whirl, the city breathes life and vitality into all who settle here, and you cannot help but be hauled along for the ride. To travel to Ho Chi Minh City is to be introduced to a dramatic meeting of old and new culture, a dynamic metropolis of skyscrapers and traffic juxtaposed with a wealth of ancient temples and traditional markets. Whether you're traveling to Ho Chi Minh City for a quick stop en route to other parts of Vietnam or are planning a visit to the city exclusively, you will be won over the city's frenetic energy and the many local gems just waiting to be discovered.",

    "Belize, Caribbean Islands" => "It's a cliché to say good things come in small packages, but with Belize it just feels right. No bigger than New Hampshire or Israel, Belize doesn't quite fit the mold of Latin America or the Caribbean, but proudly considers itself both. Belize offers a unique combination of richly rewarding experiences that make it unlike any destination on the planet. You can swim with the exotic sea life along the Western Hemisphere’s largest barrier reef, or explore the fascinating mysteries of the largest concentration of ancient Maya sites in the region. You’ll be sure to love the low-key nature of its people and the harmonious blend of cultures – Belizean, Maya, Creole, Mestizo, Garifuna, East Indian, Mennonite, Arab and Chinese that creates distinctive cultural traditions, including cuisine just waiting for you to discover.",

    "Zurich, Switzerland" => "Zurich, the largest city in Switzerland, is a major contemporary art and shopping destination. The picturesque lanes of the central Altstadt (Old Town), on either side of the Limmat River, reflect its pre-medieval history. Waterfront promenades like the Limmatquai follow the river toward the 17th-century Rathaus (town hall). Important artworks are displayed in the Kunsthaus and the Rietberg Museum. Those who consider shopping an art can hone their skills along Bahnhofstrasse and Niederdorf. Chagall's stained-glass windows in the Fraumünster amaze. Zurich's clubs and bars, including several in swimming pools, pulse with life till the early hours. This city on Lake Zurich has excellent public transport and a free bike-hire system that allows you to experience the city in a cinch.",

    "Fort Lauderdale, Florida" => "Fort Lauderdale is a city on Florida's southeastern coast, known for its beaches and boating canals. The Strip is a promenade running along the oceanside. It's lined with upscale outdoor restaurants, bars, boutiques and luxury hotels. The city's biggest draws are its stretch of gorgeous beaches, great swimming, nearly year-round sunshine and close-to-ideal climate. For great shopping, dining and nightlife, you can't go wrong at Las Olas Riverfront, a waterfront entertainment centre with top-notch clothing and jewellery shops, bars and free entertainment. The city has a host of family-friendly options, such as Everglades Holiday Park and the Museum of Discovery and Science. With the network of canals and waterways, boats are part of the Lauderdale lifestyle, and tourists can get in on the act by hiring a boat or hailing a water taxi. There's a lot to do here, but make sure and spend some quiet time just soaking up the sun or strolling along the beach at dusk.",

    "Machu Picchu, Peru" => "Machu Picchu is an awe-inspiring ancient Incan citadel set high in the Andes Mountains of Peru. This UNESCO World Heritage site, often referred to as 'The Lost City of the Incas', is one of the most familiar symbols of the Incan Empire and also one of the most famous and spectacular sets of ruins in the world. No trip to Peru, or South America for that matter, is complete without visiting this beautiful historical site. At this ancient site, you and the entire family can take a trip back through time to one of the most magnificent civilizations to ever exist.",

    "Jasper, Canada" => "Escape the urban bustle and make Jasper your home base for exploring Canada's extraordinary wilderness. As a mountain town, it's low-key and unpretentious with good food and drink. Amid the snow-capped Canadian Rockies, the park has glacier-fed lakes, forests and rivers. You can take the Jasper SkyTram which climbs to the summit of Whistlers Mountain, offering stunning views of downtown. When you're not taking in the natural beauty of Jasper, you can head to the Jasper Yellowhead Museum and Archives that present exhibits on the fur trade, railway and early exploration of the park. Jasper is an outdoor sports lover's playground, with hiking and golfing in summer and skiing and dog sledding in winter. If it's chilly, heat up at Miette Hot Springs inside Jasper National Park. You'll be sure to find that no matter the time of year, Jasper offers limitless natural beauty and fun activites for you and the entire family.",

    "Reykjavik, Iceland" => "Iceland’s biggest city, Reykjavik bears the distinction of being the world’s northernmost capital, and serves as a gateway to the city itself and to the rugged adventure options beyond. Founded in the country’s southwest at the end of the 18th century, Reykjavik has been Iceland’s cultural hub ever since. These days, that culture includes a hip and internationally recognised music and arts scene. It's home to the National and Saga museums, tracing Iceland’s Viking history. The striking concrete Hallgrimskirkja church and rotating Perlan glass dome offer sweeping views of the sea and nearby hills. Exemplifying the island’s volcanic activity is the geothermal Blue Lagoon spa, near the village of Grindavik. Reykjavík is so much more than just a destination, it’s a place of exciting possibilities surrounded by incredible landscapes, where countless adventures beckon and a host of natural wonders await.",

    "Bergen, Norway" => "Surrounded by seven hills and seven fjords, Bergen is a beguiling city. During the early Middle Ages, it was an important seaport and a member of the Hanseatic League, as well as Norway's capital– a heritage that can still be glimpsed in the beautifully colorful and preserved wooden houses of Bryggen, now protected as a Unesco World Heritage Site. You can entertain yourself in the bustling city of Bergen at its aquarium or at one of the many excellent art museums. With seven rounded lush mountains, pastel wood houses, the historic wharf, winding cobblestone streets, and Hanseatic relics, Bergen is certainly a place of enchantment.",

    "Salzburg, Austria" => "Salzburg is an Austrian city on the border of Germany, with views of the Eastern Alps. The city is divided by the Salzach River, with medieval and baroque buildings of the pedestrian Altstadt (Old Town) on its left bank, facing the 19th-century Neustadt (New Town) on its right. The storybook Old Town burrowed below steep hills looks much as it did when Mozart lived here 250 years ago. Standing beside the fast-flowing Salzach River, your gaze is raised inch by inch to graceful domes and spires, the formidable clifftop fortress and the mountains beyond. Salzburg is a city with a burgeoning arts scene, wonderful food, manicured parks, quiet side streets where classical music wafts from open windows, and concert halls that uphold musical tradition 365 days a year. Everywhere you go, the scenery, the skyline, the music and the history will surely send your spirits soaring.",

    "Cairo, Egypt" => "Cairo, Egypt’s sprawling capital, is set on the Nile River. At its heart is Tahrir Square and the vast Egyptian Museum, a trove of antiquities including royal mummies and gilded King Tutankhamun artifacts. Built near the ancient capital city of Memphis, modern Cairo is a popular starting point for cruises up the Nile and for explorations of the Pyramids at Giza just outside the city’s limits. At the world-renowned Egyptian Museum of Tahrir Square, visitors can get a close-up view of the treasure of Tutankhamun as well as mummies and other artifacts from Egypt’s ancient past. Full of vigor, Cairo is where you really get a feel for Egyptian street life. No trip to Egypt is complete without a stay in the city Arabs call Umm al-Dunya (The Mother of the World).",

    "St. Moritz, Switzerland" => "Some places on earth are simply unlike anywhere else. The mere mention of their name is strangely compelling and brings to mind all manner of stunning imagery. St. Moritz is one such place. It's a classic holiday destination. For it was here, 1,856 metres above sea level, in the heart of the spectacular Upper Engadin lakes district, that the notion of winter holidays was born. St. Moritz is the number one Alpine holiday destination. It is home to exceptional leisure and sporting facilities, culture par excellence, exclusive shopping opportunities and hosts events on the world stage. You can also look forward to internationally renowned first-class hotels and award-winning restaurants. The atmosphere is distinctly cosmopolitan and the legendary St. Moritz sun shines on average for 322 days of the year. It will take but a moment for you to find that St. Moritz offers excitement, beauty and luxury all year round.",

    "Aspen, Colorado, USA" => "This scenic mountain town is straight out of a snow globe, featuring picturesque mountain chalets hugged by the soaring Colorado Rockies. Of course, the main draw here is skiing and there are four premier ski areas nearby that cater to powder hounds of all levels. But there's more to Aspen than winter sports: With high-end shopping, fascinating museums, funky galleries and fun festivals, it might be a struggle to make it to the slopes. No matter how you choose to spend your time here, it will be a vacation you'll never forget.",

    "Whistler, Canada" => "Whistler is a town north of Vancouver, British Columbia, that's home to Whistler Blackcomb, one of the largest ski resorts in North America. The area also offers snowshoeing, tobogganing and ski jumping at the Olympic Park, a venue for the 2010 Vancouver Winter Olympics. The hub of Whistler is a compact, chalet-style pedestrian village at the base of Whistler and Blackcomb mountains. Whistler also offers a wealth of summer activities. You can lounge by a sparkling lake and admire the backdrop of the breathtaking Canadian Rocky Mountains that surrounds British Columbia. Wander through a rainforest or ride the popular Peak 2 Peak Gondola that shows you stunning 360-degree views of Whistler Village, mountain peaks, lakes, glaciers, and forests. When you want to relax, feast on new cuisine and culture every night in Whistler Village. With endless possibilties of fun and relaxtion, Whistler is the perfect destination for you and the entire family.",

    "Grindelwald, Switzerland" => "Grindelwald is postcard-perfect, a charming example of a Swiss ski resort. There are slopes for all experience levels, plus plenty of snowy activities for those who don’t ski, such as sledding, hiking or snowshoeing. Afterwards, travellers can cozy up by crackling fire and enjoy the merry atmosphere. After a long day, nothing’s better than lingering over a pot of Swiss fondue and a glass of crisp wine as you plan the next day’s adventures.",

    "Sydney, Australia" => "Sydney, capital of New South Wales and one of Australia's largest cities, is best known for its harbourfront Sydney Opera House, with a distinctive sail-like design. Massive Darling Harbour and the smaller Circular Quay port are hubs of waterside life, with the arched Harbour Bridge and esteemed Royal Botanic Garden nearby. Sydney Tower’s outdoor platform, the Skywalk, offers 360-degree views of the city and suburbs.",

    "San Juan, Puerto Rico" => "San Juan, Puerto Rico's capital and largest city, sits on the island's Atlantic coast. Its widest beach fronts the Isla Verde resort strip, known for its bars, nightclubs and casinos. Cobblestoned Old San Juan features colorful Spanish colonial buildings and 16th-century landmarks including El Morro and La Fortaleza, massive fortresses with sweeping ocean views, as well as the Paseo de la Princesa bayside promenade. From the winding streets of Old San Juan to the city's incredible beaches and sunests, San Juan can provide a stunning getaway.",

    "Orlando, Florida, USA" => "Orlando, a city in central Florida, is home to more than a dozen theme parks. Chief among its claims to fame is Walt Disney World, comprised of parks like the Magic Kingdom and Epcot, as well as water parks. Another major destination, Universal Orlando, offers Universal Studios and Islands of Adventure, with the Wizarding World of Harry Potter straddling both. Aside from the theme parks, Orlando offers hot-air balloon rides, indoor skydiving, and parasailing. Here in Orlando, there is fun for the whole family.",

    "Nice, France" => "Nice, capital of the Alpes-Maritimes department on the French Riviera, sits on the pebbly shores of the Baie des Anges. Founded by the Greeks and later turned to a retreat for the 19th-century European elite, the city's beauty has long attracted artists. You can enjoy exploring Nice's fashionable boutiques and restaurants or sunning yourself on its popular beaches. Visitors can walk up to Castle Hill for a beautiful view of the city, the Bay of Angels and of course, the bright blue water that gave the Cote d'Azur its name.",

    "Cancun, Mexico" => "Cancun, a Mexican city on the Yucatán Peninsula bordering the Caribbean Sea, is known for its beaches, numerous resorts and nightlife. Cancun is an absolute Caribbean paradise that promises romantic evenings watching the sunset, snorkeling among amazing coral reefs, shopping in local markets, discovering pre-Hispanic cultures and ruins, and dancing the night away. Whatever your travel tastes, a visit to Cancun is sure to be filled with excitement and adventure, and the beauty of the Mexican Caribbean will warm your soul.",

    "Okinawa, Japan" => "Okinawa is an island in Japan that is known for its tropical climate, broad beaches and coral reefs, as well as its World War II sites. The Okinawa Peace Memorial Museum commemorates a massive 1945 Allied invasion, and Churaumi Aquarium is home to whale sharks and manta rays. Long a popular destination for Japanese travellers looking for a relaxing beach break, Okinawa is gaining international popularity. Coral reefs provide great snorkeling and diving spots, but if you prefer to see beautiful fish without getting wet, Okinawa also has a fine aquarium. The ancient forests around the city offer a chance to view rare flora and fauna. Wherever you go in Okinawa, you'll be taken by its rich history, wonderful activites and most of all its natural beauty.",

    "Lisbon, Portugal" => "Lisbon, the capital city of Portugal, is one of the oldest cities in the world and one of Europe's most soulful, captivating and picturesque capitals, built on a series of hills with scenic vistas from every angle. It is full of bleached white limestone buildings and intimate alleyways. A short tram ride to the west of Lisbon will bring you to Belem, where you can explore attractions like the Belem Tower and the Belem Cultural Centre, which features a fantastic art collection including works by Dali, Picasso, Warhol and Magritte. In downtown Lisbon, you’ll want to visit the Gulbenkian, full of fascinating cultural artifacts and with some superb gardens in the grounds. It's possible to have a fascinating educational family holiday in Lisbon, and there are also plenty of great beaches to relax on.",

    "Kapolei, Hawaii" => "Built on former sugarcane and pineapple plantations, Kapolei is an affluent and vibrant city that is growing rapidly, and has an ever-changing urban scene. Kapolei is home to some exciting places that are unique to the area such as the Ko Olina resort and marina commuity, the Disney Aulani Resort that boast three lagoons, and a wealth of shops and restaurants. When you've spent days in the warm Pacific ocean with the sand stuck between your toes, you and the family can blast them away going down huge waterslides as Kapolei is home to the island's only water park, Hawaiian Waters Adeventure Park. Kapolei is filled with great beauty and limitless oppurtunities to have fun for you and the whole family.",

    "Antigua, Caribbean Islands" => "Antigua has hundreds of beaches, from the bustling Pigeon Point to the kitesurfing paradise of Jabberwock Beach. It's fun to mix it up—a day spent in a secluded cove, another spent people-watching at a tourist magnet. When you’re tired of sun and sand you can shoot ‘em up at Reservoir Range, where archery and air pistols are a fun way to work out any lingering pre-holiday stress. A tour of the Antigua Distillery is a spirited way to experience a true taste of the island. On Antigua, life is a beach. Its corrugated coasts that cradle scores of pefect little strands lapped by beguilling blue water to the quiant narrow roads, candy-colored villages and fine historic sights, you are sure to have a wonderful getaway.",

    "Seoul, South Korea" => "Seoul, the capital of South Korea, is a huge metropolis where modern skyscrapers, high-tech subways and pop culture meet Buddhist temples, palaces and street markets. Notable attractions include futuristic Dongdaemun Design Plaza, a convention hall with curving architecture and a rooftop park; Gyeongbokgung Palace, which once had more than 7,000 rooms; and Jogyesa Temple, site of ancient locust and pine trees. Seoul is a wonderful and richly cultured city that has something to be enjoyed by everyone.",

    "Beijing, China" => "Beijing, China’s massive capital, has history stretching back three millennia. It’s known as much for its modern architecture as its ancient sites such as the world famous Great Wall, grand Forbidden City complex, the imperial palace during the Ming (1368-1644) and Qing (1644-1912) dynasties of Ancient China. Nearby, the massive Tiananmen Square pedestrian plaza is the site of former Prime Minister Mao Zedong’s mausoleum and the National Museum of China, which displays a vast collection of cultural relics. Beijing is just one of the many beautiful culturally rich cities in China, and makes for a truly stunning, enriching and memorable vacation destination.",

    "Breckenridge, Colorado, USA" => "Breckenridge is a Colorado town at the base of the Rocky Mountains’ Tenmile Range. It's known for its ski resort, year-round alpine activities and Gold Rush history. The Victorian core of this former mining town is preserved as the Breckenridge National Historic District, running primarily along Main Street, with colorfully painted buildings from the 1880s and '90s housing shops, galleries and restaurants. Here in Breckenridge, whether you're hititng the slopes or venturing to explore the charm of Main Street, you are certain to have a serene and enjoyable getaway.",

    "Tokyo, Japan" => "Tokyo, Japan’s bustling capital, mixes the ultramodern and the traditional, from neon-lit skyscrapers to historic temples. In the Greater Tokyo Area, which is the most populous metropolitan area in the world, there is much fun to be had and beautiful sights to be seen. One of the most popular of Tokyo’s ancient sites is the opulent Meiji Shinto Shrine, which is located in the Shibuya ward of Tokyo. It is known for its spectacular and intricate towering gate and the lush forest in the surrounding area. Another popular Tokyo site is the Imperial Palace that sits amid a large and beautifully sprawling gardens. Tokyo is also home to many museums that offer exciting exhibits ranging from classical Japanese art in the Tokyo National Museum to a reconstructed kabuki theater which you can see in the Edo-Tokyo Museum. Whether you’re a history buff or just love exploring new sights and experiencing other cultures, you’re sure to have unforgettable time in Tokyo.",

    "Hong Kong" => "Futuristic skyscrapers set against a shimmering harbor, the chimes from double decker trams zipping through traffic, the smell of roast geese hanging by shop windows: Hong Kong makes a first impression like no other place on Earth. The business and financial hub proudly flaunts—and deserves—the title of “Asia’s World City.” The northern part of Hong Kong Island, together with Kowloon and Tsuen Wan New Town, forms the core urban area of Hong Kong and has an incredibly active nightlife that rivals that of New York City. The former British Crown Colony is prime for an urban adventure; from the neon-lit streets of Mongkok to the humble fishing villages in Tai O, you will never run out of sights to discover.",

    "Nepal" => "Wedged between the high Himalaya and the steamy Indian plains, Nepal has a diverse geography, including fertile plains, and subalpine forested hills. It hosts eight of the world's ten tallest mountains, including Mount Everest, the highest point on Earth. Lumbini, located in southern Nepal, is the sacred site of the birth of Gautama Buddha, the founder of Buddhism. Nepal is full of history, religion, and culture. Here in Nepal, you’ll have an absolutely breathtaking and unforgettable experience.",

    "Huangshan, China" => "Huangshan (Yellow Mountain) is a mountain range in eastern China. The area is well known for its scenery, sunsets, and peculiarly-shaped granite peaks, some more than 1,000 meters high. It is also home to hot springs, winter snow, and views of the clouds from above. Yellow Mountain is a frequent subject of traditional Chinese paintings and literature, as well as modern photography. It is a UNESCO World Heritage Site, and one of China's major tourist destinations. It is a region with a long history and spledid culture. A vacation to Huangshan will be one of the most remarkable and unforgettable experiences of your life.",

    "Tibet" => "Tibet enchants tourists from China and abroad with its landscape, religious traditions, culture, and its unsolved mysteries. At any mention of this land, the images of snowy mountains, mirror-like lakes, Potala Palace and Buddhist disciples immediately come to mind. Tibet is nicknamed the “Roof of the World” for its towering peaks, particularly Mount Everest, the world’s tallest peak. Its capital, Lhasa, is site of hilltop Potala Palace, once the Dalai Lama’s winter home, and Jokhang Temple, Tibet’s spiritual heart, revered for its golden statue of the young Buddha. Whether you're seeking spiritual enlightenment or just want to experience one of the most beautiful places on the planet, You'll surely be transformed by a visit to Tibet.",

    "Grand Canyon National Park, Arizona, USA" => "Grand Canyon National Park, in Arizona, is home to much of the immense Grand Canyon, with its layered bands of red rock revealing millions of years of geological history. A popular place to enjoy the Grand Canyon is Lipan Point. Lipan Point offers wide scenic views of the canyon and the Colorado River, and is especially charming at sunrise and sunset. Vast, magnificent and inarguably beautiful, the Grand Canyon is easily Arizona’s most distinguishable landmark – and a natural wonder that you simply have to see to believe.",

    "Anchorage, Alaska, USA" => "Anchorage, Alaska is known for its cultural sites, including the Alaska Native Heritage Center, which displays traditional crafts, stages dances, and presents replicas of dwellings from the area’s indigenous groups. From the sparkling waters of Cook Inlet to the tallest peaks of the Chugach Mountains, Anchorage encompasses incredible adventures and metropolitan appeals that are larger than life. With 1,500 moose, incredible national parks nearby and 60 glaciers a short drive away, it's a dream destination in Alaska.",

    "Portland, Oregon, USA" => "Portland is Oregon’s largest city, known for being laid-back and friendly. With a reputation for manicured parks, eclectic nightlife, fine micro-breweries and distilleries, and nature that cuts right into the city, Portland is a Pacific Northwest must-visit. With parks, bridges, and bicycle paths, you can easily explore the eco-friendly city’s breweries, coffeehouses, and the famous Japanese Garden, one of the largest and most beautiful of its kind outside of Japan.",

    "Negril, Jamaica" => "Negril is a town in western Jamaica. It’s known for its miles of sandy beaches on shallow bays with calm, turquoise waters. Seven Mile Beach, particularly the portion overlooking Long Bay, is lined with bars, restaurants and resorts, many of them international and all-inclusive. Long Bay opens onto a lagoon protected by coral reefs and is a snorkeling and scuba-diving destination. Negril is a stunning combination of landscapes that cannot be found anywhere else on the island. The locals have dubbed this city the 'Capital of Casual' for its informal island vibe. In this laid back paradise, you'll be sure to have a wondeful time.",

    "Scheveningen, The Netherlands" => "Scheveningen is Holland’s most famous seaside resort with an abundance of attractions and beach pavilions. You can take a stroll along the sandy beach, promenade, and pier, and enjoy the marine world at Sea Life. The beach is popular for water sports such as windsurfing and kiteboarding. In the city center, you can enjoy the sunset dining or dance the night away.",

    "Rio de Janeiro, Brazil" => "Rio de Janeiro is a huge seaside city in Brazil, famed for its Copacabana and Ipanema beaches, Christ the Redeemer statue atop Mount Corcovado and for Sugarloaf Mountain, a granite peak with cable cars to its summit. The city is aslo known for its raucous Carnaval festival, featuring parade floats, flamboyant costumes and samba dancers, and is considered the world’s largest. With breathtaking views from Corcovado Mountain and breathtaking deals in the city’s endless malls and markets, Rio de Janeiro is a holiday paradise.",

    "Santorini, Greece" => "Santorini, a volcanic island in the Cyclades that rests in the middle of the Aegean, is one of the most popular tourist destinations in Greece- and for good reason. Travel to Santorini and you will be treated to sweeping, dramatic ocean views, pristine beaches, including the black pebble beach of Kamari, traditional Grecian architecture, fine dining, and numerous, excellent local wineries. The island's local charm and beauty make Santorini travel an unforgettable experience ",

    "Wildwood, New Jersey, USA" => "Wildwood is a popular summer resort destination with miles of white sand beaches that are perfect for swimming, soaking up the sun and relaxing on a hot summer day. If you're looking for adventure, the Wildwoods’ beaches also serve as an ideal location for surfing, boogie boarding, power boating, jet skiing, sailing, and kayaking. The boardwalk offers excitement with rides, waterparks, shopping and arcades, plus great dining and nightlife. Wildwood is lauded as one of the best family destinations. ",

    "Tel Aviv, Israel" => "Tel Aviv, a youthful, modern metropolis with a diverse population, is marked by stark 1930s Bauhaus buildings, thousands of which are clustered in the White City architectural area. Clubs, bars, a thriving arts community, and beaches attract artists, musicians and young professionals to Tel Aviv's more secular scene. Walk, drive or take cabs between the cultural exhibition pavilions of Haaretz Museum, historic Independence Hall Museum, bustling Carmel Market and Old Jaffa's boardwalk. Tel Aviv’s multimedia exhibits illustrate the history of Jewish communities worldwide. The Eretz Israel Museum covers the country’s archaeology, folklore and crafts, and features an on-site excavation of 12th-century-B.C. ruins. A getaway to this beautiful city, with its rich culture and beautiful sights, is sure to be a most memorable one.",

    "Ko Lanta, Thailand" => "Ko Lanta is a gorgeous island where you'll be certain to find an uncrowded beach. Located in the Krabi Province, one of the southern provinces of Thailand, Ko Lanta offers fantastic scuba diving with exotic marine life and grand coral reefs. It’s known for its coral-fringed beaches, mangroves, limestone outcrops and rainforests. Ko Lanta's beaches are known to offer the most legendary views of sunsets. With its quiet charm and natural beauty, you'll definitely enjoy your time spent here.",

    "Guadeloupe" => "Guadeloupe is an archipelago of islands in the southern Caribbean sea where you will find hundreds of different activities to pick from. Resembling a butterfly, its two main islands include Grande-Terre, where beach towns offer white sands, sugarcane fields and a variety of water activities, and the mountainous Basse-Terre, where you can visit the breathtaking Guadeloupe National Park, which is home to the volcano La Grand Soufrière. Guadeloupe is a bit of France miles away from St-Tropez. Afro-influences are more pronounced here, especially in the potpourri of spices that perfume the island’s plentiful outdoor markets. You cannot go wrong with a vacation to this beauitful multiculturally influenced paradise.",

    "Coral Coast, Fiji" => "Coral Coast is the stretch of coastline on the island of Viti Levu, in Fiji. This stretch of coast is one of Fiji's tourist areas with resorts located in various locations along the coast and on islands just off the coast. Coral Coast offers both the full resort experience and a chance to visit the real Fiji in the many villages along the way. Golf, beach life and diving are there for the taking, but for those of you who seek a more authentic experience, many villages operate home stays. From a fisherman selling his day’s catch on the roadside, to bargaining with a local at the Sigatoka Market, true island life is here.",

    "St Martin, Caribbean Islands" => "Saint Martin is part of the Leeward Islands in the Caribbean Sea with a spicy marriage of Caribbean, French and Dutch cultures that match its physical diversity. The island is both urban and untamed, with rain forest-like landscapes, white beaches, and amazing caves and wildlife. It is home to busy resort beaches and secluded coves. It's also known for fusion cuisine, vibrant nightlife and duty-free shops selling jewelry and liquor. Combining all Saint Martin has to offer - mix well - and we know you'll find the perfect recipe for your perfect vacation."
);

?>
